name: Testing
on: [push]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Unit Tests
        run: npm run test -- --watchAll=false
      - name: E2E tests
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
